### Login

POST http://localhost:3000/api/login
Content-Type: application/json;charset=utf-8

{
    "email":"correo@iteso.mx",
    "password":"pass"
}

### Get Users

GET http://localhost:3000/api/users
Content-Type: application/string;charset=utf-8

{

}
### Get User wit email

GET http://localhost:3000/api/users/correo@iteso.mx

{

}


### Edit User

PUT http://localhost:3000/api/users/correo@iteso.mx
Content-Type: application/json;charset=utf-8

{
    "email":"correo@iteso.mx",
    "password":"diego"
}
