### Read Channel Feed
GET https://api.thingspeak.com/channels/1023068/feeds.json?api_key=OFB0NR74DCYEUVNX&results=2
Content-Type: application/json

### Read a Channel Field
GET https://api.thingspeak.com/channels/1023068/fields/1.json?api_key=OFB0NR74DCYEUVNX&results=2
Content-Type: application/json

### Read Channel Status Updates
GET https://api.thingspeak.com/channels/1023068/status.json?api_key=OFB0NR74DCYEUVNX
Content-Type: application/json

### Write a Channel Feed
GET https://api.thingspeak.com/update?api_key=O7YT8XMI4GG4HO0K&field1=0
Content-Type: application/json


### SERVER USER
PUT http://localhost:3000/users/
Content-Type: application/json